spring:
  datasource:
    username: root
    password: dxy123456
    url: jdbc:mysql://47.108.196.209:3306/meets?characterEncoding=utf8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
